### ISSUE TITLE
Paragraph formatting issue

### ISSUE THREAD

**Issue by fbob** [MizarZh/mathlive-in-editor-mode#2] opened 2024-07-02 08:23 UTC
Hi,

It seems that the paragraph formatting is messed up when using the plugin.
Enabling Mathlive display reformats the paragraph correctly but when the cursor returns inside the equation in obsidian the formatting is messed up again.

Good :
![image](https://github.com/MizarZh/mathlive-in-editor-mode/assets/8211124/778d5945-a263-4298-8b1d-e058ed039672)

Bad :
![image](https://github.com/MizarZh/mathlive-in-editor-mode/assets/8211124/0bd42e53-f1e3-4c92-901e-0e7fbd790fcc)

**Comment by MizarZh** [comment] 2024-07-07 06:51
I cannot reproduce the result. It seems normal in my editor with or without the cursor inside.

![image](https://github.com/MizarZh/mathlive-in-editor-mode/assets/52587907/8464975f-622b-4679-9e79-62ff9153a8dc)

Can you show it with a gif or video?

**Comment by fbob** [comment] 2024-07-07 16:11
Here is a video illustrating the behavior

https://github.com/MizarZh/mathlive-in-editor-mode/assets/8211124/42a4c122-1e00-4377-8fdb-3223c46f1bde

Tanks

**Comment by MizarZh** [comment] 2024-07-07 17:49
Fixed in release 0.1.7

**Closed by MizarZh** 2024-07-07 17:49 UTC

**Comment by fbob** [comment] 2024-07-07 19:12
Works perfectly.
Many thanks and awesome plugin !
